# This is a basic workflow to help you get started with Actions

name: iOS

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos-14_ios:
    name: iOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphonesimulator
      - run: cmake --build b --config Release --target cpp-tests -- -quiet -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)"

