# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-20_04:
    name: Ubuntu24
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: echo -e "y" | bash install-deps-linux.sh
      - run: cmake -B b -S .
      - run: cmake --build b

  windows-2022:
    name: Win64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -G "Visual Studio 17 2022" -A x64
      - run: cmake --build b

  macos-14:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode
      - run: cmake --build b 

  macos-14_ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphonesimulator
      - run: cmake --build b --config Release --target cpp-tests -- -quiet -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)"

