# This is a basic workflow to help you get started with Actions

name: Win64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-2022:
    name: Windows64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -G "Visual Studio 17 2022" -A x64
      - run: cmake --build b
